/**
 * CENTRAL GAME CONFIGURATION
 * Add one object here to publish a game across Discover, New Releases,
 * related games and the browser-games directory.
 */
const GAMES = [
  { id:"neon-boss-rush", name:{es:"Neon Boss Rush",pt:"Neon Boss Rush",en:"Neon Boss Rush"}, url:"https://felipecostudios.github.io/NeonBossRush/", genre:"Action", tags:["Action","Arcade","Boss"], description:{es:"Boss rush 3D con jefes caóticos, héroes y power-ups.",pt:"Boss rush 3D com chefes caóticos, heróis e power-ups.",en:"A 3D boss rush with chaotic bosses, heroes and power-ups."}, image:"assets/game-previews/neon-boss-rush.svg", difficulty:4, date:"2026-09-14", updated:true, featured:true, keywords:"action, arcade, boss rush, neon, 3D", relatedTags:["Action","Arcade"] },
  { id:"vital-smash-4p", name:{es:"Vital Smash 4P",pt:"Vital Smash 4P",en:"Vital Smash 4P"}, url:"https://felipecostudios.github.io/VitalSmash4PV/", genre:"Action", tags:["Action","Casual","Multiplayer"], description:{es:"Versión multijugador de Vital Smash para partidas locales de hasta cuatro jugadores.",pt:"Versão multiplayer de Vital Smash para partidas locais de até quatro jogadores.",en:"A multiplayer version of Vital Smash for local games with up to four players."}, image:"assets/game-previews/vital-smash-4p.svg", difficulty:2, date:"2026-09-02", updated:true, featured:false, keywords:"action, multiplayer, local, 4 player", relatedTags:["Action","Casual"] },
  { id:"vital-smash", name:{es:"Vital Smash",pt:"Vital Smash",en:"Vital Smash"}, url:"https://felipecostudios.github.io/VitalSmash/", genre:"Action", tags:["Action","Casual","Education"], description:{es:"Juego educativo de acción inspirado en los Objetivos de Desarrollo Sostenible.",pt:"Jogo educativo de ação inspirado nos Objetivos de Desenvolvimento Sustentável.",en:"An educational action game inspired by the Sustainable Development Goals."}, image:"assets/game-previews/vital-smash.svg", difficulty:2, date:"2026-09-01", updated:false, featured:false, keywords:"education, action, SDG, sustainability", relatedTags:["Action","Education"] },
  { id:"resenha-fut-9c", name:{es:"Resenha Fut 9C",pt:"Resenha Fut 9C",en:"Resenha Fut 9C"}, url:"https://felipecostudios.github.io/PietroNiver/", genre:"Sports", tags:["Sports","Arcade","Action"], description:{es:"Fútbol arcade caótico con IA, cooperativo local e ítems inesperados.",pt:"Futebol arcade caótico com IA, cooperativo local e itens inesperados.",en:"Chaotic arcade football with AI, local co-op and unexpected items."}, image:"assets/game-previews/resenha-fut-9c.svg", difficulty:3, date:"2026-08-10", updated:false, featured:false, keywords:"football, soccer, sports, arcade, multiplayer", relatedTags:["Sports","Arcade"] },
  { id:"tomato-smash", name:{es:"Tomato Smash",pt:"Tomato Smash",en:"Tomato Smash"}, url:"https://tomatosmash.netlify.app/", genre:"Arcade", tags:["Arcade","Action","Casual"], description:{es:"Aplasta tomates, encadena combos y supera tus mejores marcas.",pt:"Esmague tomates, faça combos e supere suas melhores marcas.",en:"Smash tomatoes, chain combos and beat your best scores."}, image:"assets/game-previews/tomato-smash.svg", difficulty:2, date:"2026-08-05", updated:false, featured:false, keywords:"arcade, tomato, casual, score", relatedTags:["Arcade","Casual"] },
  { id:"the-6-warriors", name:{es:"The 6 Warriors",pt:"The 6 Warriors",en:"The 6 Warriors"}, url:"https://the6warriors.netlify.app/", genre:"Action", tags:["Action","Arcade","Survival"], description:{es:"Sobrevive a oleadas con seis guerreros, bosses, XP y habilidades.",pt:"Sobreviva a ondas com seis guerreiros, chefes, XP e habilidades.",en:"Survive waves with six warriors, bosses, XP and abilities."}, image:"assets/game-previews/the-6-warriors.svg", difficulty:3, date:"2026-07-20", updated:true, featured:false, keywords:"action, survival, warriors, waves, boss", relatedTags:["Action","Arcade"] },
  { id:"goofy-boxes", name:{es:"Goofy Boxes",pt:"Goofy Boxes",en:"Goofy Boxes"}, url:"https://goofyboxies.netlify.app/", genre:"Casual", tags:["Casual","Collector","Arcade"], description:{es:"Abre cajas absurdas, colecciona cosas y desbloquea logros.",pt:"Abra caixas absurdas, colecione coisas e desbloqueie conquistas.",en:"Open ridiculous boxes, collect things and unlock achievements."}, image:"assets/game-previews/goofy-boxes.svg", difficulty:1, date:"2026-07-01", updated:false, featured:false, keywords:"casual, collector, boxes, achievements", relatedTags:["Casual","Arcade"] },
  { id:"custom-clicker", name:{es:"Custom Clicker",pt:"Custom Clicker",en:"Custom Clicker"}, url:"https://customclicker4u.netlify.app/", genre:"Casual", tags:["Casual","Idle","Clicker"], description:{es:"Un clicker simple con producción y mejoras para seguir creciendo.",pt:"Um clicker simples com produção e melhorias para continuar crescendo.",en:"A simple clicker with production and upgrades to keep growing."}, image:"assets/game-previews/custom-clicker.svg", difficulty:1, date:"2026-06-15", updated:false, featured:false, keywords:"idle, clicker, casual, incremental", relatedTags:["Casual"] },
  { id:"supra-meirro", name:{es:"Supra Meirro",pt:"Supra Meirro",en:"Supra Meirro"}, url:"https://14yearoldcoding.neocities.org/", genre:"Arcade", tags:["Arcade","Action","Retro"], description:{es:"Una experiencia arcade retro con controles simples y niveles para explorar.",pt:"Uma experiência arcade retrô com controles simples e níveis para explorar.",en:"A retro arcade experience with simple controls and levels to explore."}, image:"assets/game-previews/supra-meirro.svg", difficulty:2, date:"2026-05-20", updated:false, featured:false, keywords:"arcade, retro, action, platform", relatedTags:["Arcade","Action"] }
];
function getFeaturedGame(){ return GAMES.find(g=>g.featured) || GAMES[0]; }
function getNewReleases(limit=6){ return [...GAMES].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,limit); }
function getUpdatedGames(limit=6){ return GAMES.filter(g=>g.updated).slice(0,limit); }
function getRelatedGames(gameId,limit=3){ const game=GAMES.find(g=>g.id===gameId); if(!game)return []; return [...GAMES].filter(g=>g.id!==gameId).map(g=>({game:g,score:(g.tags||[]).filter(t=>(game.relatedTags||[]).includes(t)).length})).sort((a,b)=>b.score-a.score||new Date(b.game.date)-new Date(a.game.date)).slice(0,limit).map(x=>x.game); }
function getGameUrl(gameId){ return `/games/${gameId}/`; }
